name: Generate Sitemap for Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1. Generate sitemap.xml in the root of the repo
      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          find . -name "*.html" -not -path "./.github/*" -not -name "sitemap.xml" | while read file; do
            path=$(echo $file | sed 's|^\./||')
            echo "  <url><loc>https://borderbarrels.com/$path</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      # 2. (Optional) Deploy to Netlify via Netlify CLI
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '.'        # folder containing index.html and sitemap.xml
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
