name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install sitemap generator
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap
        run: sitemap-generator https://borderbarrels.com -o ./sitemap.xml
