name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # ensures push works using the token

      - name: Generate dynamic sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          find . -name "*.html" -not -path "./.github/*" -not -name "sitemap.xml" | while read file; do
            path=$(echo $file | sed 's|^\./||')
            url="https://borderbarrels.com/$path"
            echo "  <url><loc>$url</loc></url>" >> sitemap.xml
          done
          
          echo '</urlset>' >> sitemap.xml

      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
